apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment
  labels:
    app: my-k8s-application
    env: prod
    owner: VadimBobylov
spec:
  replicas: 2
  selector:
    matchLabels:
      project: kgb
  template:
    metadata:
      labels:
        project: kgb
    spec:
      containers:
        - name: kgb-web
          image: vadim1bobylov/springk8s:latest
          ports:
            - containerPort: 8080
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1v1
    kind: Deployment
    name: my-web-deployment
  minReplicas: 3
  maxReplicas: 5
  metrics:
   - type: Resource
     resource:
       name: cpu
       targetAverageUtilization: 70
   - type: Resource
     resource:
       name: memory
       targetAverageUtilization: 80