apiVersion: v1
kind: Pod
metadata:
  name: spring-demo
  labels:
    env: prod
    app: main
    tier: backend
    owner: VadimBobylov
spec:
  containers:
    - name: sping-container
      image: vadim1bobylov/springk8s:latest
      ports:
        - containerPort: 8080
    - name: container-apache
      image: httpd:latest
      ports:
        - containerPort: 80