#create deployments
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment
  labels:
    app: my-k8s-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      project: cia
  template:
    metadata:
      labels:
        project: cia #service will look for those pods labels
    spec:
      containers:
        - name: my-php-web
          image: vadim2bobylov/k8s:php
          ports:
            - containerPort: 80 #pod port
        - name: my-sring-web
          image: vadim1bobylov/springk8s:v2
          ports:
            - containerPort: 8080 #pod port
---
#create services
apiVersion: v1
kind: Service
metadata:
  name: my-multi-service
  labels:
    env: prod
    owner: VadimBobylov
spec:
  selector:
    project: cia # selecting pods with those labels
  ports:
    - name: app-multi-listener-php
      protocol: TCP
      port: 7777 # port on load balancer
      targetPort: 80 # port on POD
    - name: app-multi-listener-spring
      protocol: TCP
      port: 8888 # port on load balancer
      targetPort: 8080 # port on POD
  type: LoadBalancer # define type